interface Props {
  recommendation: string;
  savings: number;
  yearlySavings: number;
  reason: string;
}

export default function DownloadReportButton(
  props: Props
) {

  const handleDownload = () => {

    const report = `
AI COST OPTIMIZATION REPORT

----------------------------------

Recommendation:
${props.recommendation}

Monthly Savings:
$${props.savings}

Yearly Savings:
$${props.yearlySavings}

Reason:
${props.reason}

----------------------------------

Generated by Credex AI Audit Platform
`;

    const blob = new Blob(
      [report],
      { type: "text/plain" }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "ai-audit-report.txt";

    link.click();

    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="mt-8 w-full bg-cyan-400 text-black py-4 rounded-xl font-semibold hover:bg-cyan-300 transition"
    >
      Download AI Audit Report
    </button>
  );
}